# Токен бота
BOT_TOKEN = "..."


# IDs администраторов
ADMIN_IDS = [...]

(CHOOSING, TYPING_NAME, TYPING_EXAM, DELETING, STUDENT_LOGIN, STUDENT_MENU, ADD_VARIANT, ADD_VARIANT_LINK,
 TYPING_CLASS_LINK, TYPING_CLASS_DATE, CHOOSING_FIELD, UPDATING_FIELD, CONFIRMATION, ADD_TASK, ADD_TASK_TITLE,
 ADD_TASK_LINK, DELETE_TASK, SELECT_TASK_TO_DELETE, UPDATING_TASK_FIELD,
 EDIT_TASK_CHOOSE_EXAM, EDIT_TASK_CHOOSE_TASK, EDIT_TASK_CHOOSE_FIELD,
 EDIT_TASK_UPDATE_FIELD, EDIT_TASK_CONFIRM_UPDATE, TYPING_HOMEWORK_LINK,
 ADD_NOTE, ADD_NOTE_TITLE, ADD_NOTE_LINK, EDIT_NOTE_CHOOSE_NOTE, EDIT_NOTE_CHOOSE_EXAM, EDIT_NOTE_CHOOSE_FIELD,
 EDIT_NOTE_UPDATE_FIELD, EDIT_NOTE_CONFIRM_UPDATE, HOMEWORK_LINK, CONFIRM_HOMEWORK_LINK) = range(35)

# Добавляем всё в __all__
__all__ = [
    "BOT_TOKEN",
    "ADMIN_IDS",
    "CHOOSING", "TYPING_NAME", "TYPING_EXAM", "DELETING", "STUDENT_LOGIN", "STUDENT_MENU",
    "ADD_VARIANT", "ADD_VARIANT_LINK", "TYPING_CLASS_LINK", "TYPING_CLASS_DATE",
    "CHOOSING_FIELD", "UPDATING_FIELD", "CONFIRMATION",
    "ADD_TASK", "ADD_TASK_TITLE", "ADD_TASK_LINK",
    "DELETE_TASK", "SELECT_TASK_TO_DELETE", "UPDATING_TASK_FIELD",
    "EDIT_TASK_CHOOSE_EXAM", "EDIT_TASK_CHOOSE_TASK", "EDIT_TASK_CHOOSE_FIELD",
    "EDIT_TASK_UPDATE_FIELD", "EDIT_TASK_CONFIRM_UPDATE", "TYPING_HOMEWORK_LINK",
    "ADD_NOTE", "ADD_NOTE_TITLE", "ADD_NOTE_LINK", "EDIT_NOTE_CHOOSE_EXAM", "EDIT_NOTE_CHOOSE_NOTE",
    "EDIT_NOTE_CHOOSE_FIELD", "EDIT_NOTE_UPDATE_FIELD", "EDIT_NOTE_CONFIRM_UPDATE",
    "HOMEWORK_LINK", "CONFIRM_HOMEWORK_LINK"
]
